apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "privacyidea.fullname" . }}-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ include "privacyidea.fullname" . }}-service
                port:
                  number: 5000
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}