apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacyidea.fullname" .}}-admin-account-config
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
type: Opaque
data:
  PRIVACYIDEA_ADMIN_USER: {{ .Values.privacyidea.adminUser | b64enc | quote}}
  PRIVACYIDEA_ADMIN_PASSWORD: {{ include "privacyidea.encryptedAdminPassword" .}}