apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "privacyidea.mysql" . }}"
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ include "privacyidea.mysql.encryptedRootPassword" . }}
  MYSQL_USER: {{ .Values.mysql.username | b64enc | quote }}
  MYSQL_PASSWORD: {{ include "privacyidea.mysql.encryptedPassword" .}}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc | quote }}