apiVersion: v1
kind: Service
metadata:
  name: "{{ template "privacyidea.mysql" . }}"
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
spec:
  ports:
    - port: 3306
  selector:
{{ include "privacyidea.selectorLabels" . | indent 4 }}
    component: database